version: "3"

services:
  db:
    image: postgres:16
    ports:
      - "54322:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: feedbin
    volumes:
      # Mount the Postgres data directory so it persists between runs
      - db-data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
